apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-auth-ingress
spec:
  rules:
  - host: simple-auth.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth
            port: 
              number: 8080