apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP # ip address assigned to this service is going to be accessible within our cluster
  clusterIP: 10.96.0.3
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP